# Generated by Django 4.0.4 on 2022-05-19 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sexo', models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino')], max_length=1, verbose_name='Sexo')),
                ('documento', models.CharField(max_length=12, verbose_name='Documento de identidade')),
                ('divisao', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio')], max_length=11, verbose_name='Divisão educacional')),
                ('email', models.EmailField(max_length=20, verbose_name='Email de contato')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro do cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('livro', 'Livro'), ('dvd', 'DVD/CD/BLUE-RAY'), ('jornal', 'Jornal'), ('revista', 'Revista')], max_length=8, verbose_name='Tipo do material')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo do material')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('descricao', models.TextField(max_length=1000, verbose_name='Descrição do material')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('armario', models.CharField(choices=[('A', 'Armário A'), ('B', 'Armário B'), ('C', 'Armário C')], max_length=8, verbose_name='Localização do Livro no armário')),
                ('prateleira', models.CharField(choices=[('1', 'Prateleira 1'), ('2', 'Prateleira 2'), ('3', 'Prateleira 3')], max_length=8, verbose_name='Localização do Livro na prateleira')),
                ('dataposse', models.DateTimeField(blank=True, max_length=10, verbose_name='Data de Registro do empréstimo')),
                ('posse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
            ],
        ),
    ]
